# spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#spring:
 # datasource:
  #  url: local
    
    
    
    
    ##jdbc:h2:mem:testdb